enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

[YouTube]
build-mode = "both"
included-patches = "'Custom branding' 'Change header'"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"

# [YouTube-Extended]
# patches-source = "inotia00/revanced-patches"
# integrations-source = "inotia00/revanced-integrations"
# cli-source = "inotia00/revanced-cli"
# rv-brand = "RinaTube Extended"
# build-mode = "both"
# included-patches = "'Custom branding icon YouTube' 'Custom branding name YouTube' 'Theme'"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
