enable-magisk-update = true
parallel-jobs = 2
remove-rv-integrations-checks = false

[YouTube]
build-mode = "both"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
patcher-args = "-e 'Custom branding' -OcustomName='RinaTube' -OcustomIcon='./rina/custom-branding/' -e 'Change header' -Ocustom='./rina/change-header/' -e 'Theme' -OdarkThemeBackgroundColor='#FF290025' -OlightThemeBackgroundColor='#FFFCCFF3' "
