[YouTube]
build-mode = "both"
included-patches = "'Custom branding' 'Change header'"
version = "auto"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube" # fallback

# [YouTube-Extended]
# patches-source = "inotia00/revanced-patches"
# integrations-source = "inotia00/revanced-integrations"
# cli-source = "inotia00/revanced-cli"
# rv-brand = "RinaTube Extended"
# build-mode = "both"
# included-patches = "'Custom branding icon YouTube' 'Custom branding name YouTube' 'Theme'"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
